### ISSUE TITLE
Solving MX set_class function issue

### ISSUE THREAD

**Issue by arnezt** [agoenks29D/My-Igniter#1]
Hanya tambahan masalah fungsi set_class pada MX:
```php
public function set_class($class)
{
	$suffix = $this->config->item('controller_suffix');

	if ($suffix && strpos($class, $suffix) === FALSE) {
		$class .= $suffix;
	}

	parent::set_class($class);
}
```

**Comment by agoenks29D** [comment]
Masalahnya apa ya? saya rasa cuman perbedan ```&&``` saja pada file [third_party/MX/Router.php](https://github.com/agoenks29D/My-Igniter/blob/master/application/third_party/MX/Router.php#L236)

**Comment by arnezt** [comment]
> Masalahnya apa ya? saya rasa cuman perbedan `&&` saja pada file [third_party/MX/Router.php](https://github.com/agoenks29D/My-Igniter/blob/master/application/third_party/MX/Router.php#L236)

Yang jelas error di PHP 7.3 silahkan dicoba.. itu hanya masukan klo mungkin ada yang mengalami hal yang sama dengan saya. Thanks.

**Comment by agoenks29D** [comment]
Terimakasih masukannya mas..

**Comment by arnezt** [comment]
> Terimakasih masukannya mas..

Sama-sama bro..
